export const FETCH_MOCK_EXAMPLE = 'mock/FETCH_MOCK_EXAMPLE';

export const LOAD_MOCK_EXAMPLE_START = 'mock/LOAD_MOCK_EXAMPLE_START';
export const LOAD_MOCK_EXAMPLE_SUCCESS = 'mock/LOAD_MOCK_EXAMPLE_SUCCESS';
export const LOAD_MOCK_EXAMPLE_ERROR = 'mock/LOAD_MOCK_EXAMPLE_ERROR';
