import { Fragment, useState } from 'react';
import { useQuery } from 'react-query';
import { CopyToClipboard } from 'react-copy-to-clipboard';
import { FiExternalLink } from 'react-icons/fi';

import { fetchAbout } from 'Common/API';
import Preloader from 'Components/Preloader';
import Version from 'Components/Version';
import Formatted from 'Components/Formatted';

// import AboutWebsite from './Website';

import './style.less';

const EMAIL = process.env.REACT_APP_EMAIL;
console.log(process.env.REACT_APP_EMAIL)

function About() {
  const { data: { data } } = useQuery('About', () => fetchAbout());
  const [isCopied, setIsCopied] = useState(false);
  
  return (
    <Fragment>
      <div className={'About About_dark'}>
        <h1>{data.title}</h1>
        <Formatted>
          {data.intro}
        </Formatted>
        <ul>
          <li>
            <a href="https://drive.google.com/file/d/155imY9utcyQEj68yxZL3V0ygnyjlwpMw/view" target="_blank">My CV in PDF at Google Drive <FiExternalLink /></a>
          </li>
          <li>
            <a href="https://drive.google.com/file/d/1by9rcRYvHE_gmLLM5BH71XhC8L_W4KLd/view" target="_blank">Developer Story <FiExternalLink /></a>
            {!isCopied ? ' ' : '. '}
            {
              !isCopied ?
              <>
                and maybe you need
                {' '}
                <CopyToClipboard 
                  text={EMAIL}
                  onCopy={() => setIsCopied(true)}
                >
                  <span style={{cursor: 'pointer', textDecoration: 'underline'}}>
                    to copy my email.
                  </span>
                </CopyToClipboard>
              </>
              :
              <span>Email is in a clipboard: <a href={`mailto:${EMAIL}`}>{EMAIL}</a></span>
            }
          </li>
          <li>
            <a href="https://github.com/shapkarin" target="_blank" rel="noreferrer">My Github <FiExternalLink /></a>
          </li>
        </ul>
        <br />
        <a href='https://github.com/shapkarin/shapkarin.me' target='_blank' rel='noreferrer'>Website source code<FiExternalLink /></a> <Version number/> 
        <br/><br/>
        PS: This site API is generated by <a href="https://github.com/shapkarin/shapkarin.me/tree/master/src/Generate-Backend" target="_blank">this code</a><FiExternalLink /> and stored as JSON files.
      </div>
    </Fragment>
  )
}



export default function SuspensedAbout() {
  return <Preloader><About /></Preloader>
}