export const FETCH_REPOSITORIES = 'github/FETCH_REPOSITORIES';

export const LOAD_REPOSITORIES_START = 'github/LOAD_REPOSITORIES_START';
export const LOAD_REPOSITORIES_SUCCESS = 'github/LOAD_REPOSITORIES_START';
export const LOAD_REPOSITORIES_ERROR = 'github/LOAD_REPOSITORIES_START';
