export const FETCH_PROJECTS = 'projects/FETCH_PROJECTS';
export const FETCH_PROJECT_INFO = 'projects/FETCH_PROJECT_INFO';

export const LOAD_PROJECTS_START = 'projects/LOAD_PROJECTS_START';
export const LOAD_PROJECTS_SUCCESS = 'projects/LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_ERROR = 'projects/LOAD_PROJECTS_ERROR';

export const LOAD_PROJECT_INFO_START = 'projects/LOAD_PROJECT_INFO_START';
export const LOAD_PROJECT_INFO_SUCCESS = 'projects/LOAD_PROJECT_INFO_SUCCESS';
export const LOAD_PROJECT_INFO_ERROR = 'projects/LOAD_PROJECT_INFO_ERROR';
