name: Reusable job

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: "Deployment target: gh-pages or s3-unchained"

jobs:
  call-gh-pages:
    if: inputs.target == 'gh-pages'
    uses: ./.github/workflows/gh-pages.yml

  call-s3-unchained:
    if: inputs.target == 's3-unchained'
    uses: ./.github/workflows/s3-unchained.yml
    secrets: inherit
