name: Deploy on changes in main

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".dockerignore"
      - "Dockerfile.local"
      - "compose.local.yaml"

jobs:
  call-deploy:
    uses: ./.github/workflows/job.yml
    secrets: inherit
